"""
see `../__init__.py`.
"""
from .typing_stub import Component
from .typing_stub import props
from .typing_stub import wprops

__all__ = ['C', 'P', 'W', 'qml_namespace', 'setup']

qml_namespace = set()  # type: set[str]

C = Component
P = props
W = wprops

""" C: class Component.
    P: properties package. the only usage is `P.PropSheet`. see also
        `qmlpy.properties.core.prop_sheet.PropSheet`.
    W: widget oriented properties. we have implemented a list of detailed
        properties for EACH widget (that is a very long list, heavily auto-
        generated by blueprint). using `W.Ps<WidgetName>` to get the list.
"""


def setup(**kwargs) -> None:
    global C, P, W
    C = kwargs['component']
    P = kwargs['properties']
    W = kwargs['widget_properties']
